Try freeze 5 times
Signed-off-by: Qi Luo <qiluo-msft@users.noreply.github.com>

diff --git a/scripts/fast-reboot b/scripts/fast-reboot
--- a/scripts/fast-reboot
+++ b/scripts/fast-reboot
@@ -82,11 +82,16 @@ fi
 
 if [[ "$REBOOT_TYPE" = "warm-reboot" ]]; then
     # Freeze orchagent for warm restart
-    # Note: assume that 5 seconds is enough for orchagent to process the request and freeze, otherwise we treat the system as non-warm-reboot-able
-    docker exec -i swss /usr/bin/orchagent_restart_check -w 5000 || {
-        echo "RESTARTCHECK failed\n" >&2
-        exit 10
-    }
+    # Try freeze 5 times, it is possible that the orchagent is in transient state and no opportunity to be freezed
+    # Note: assume that 1 second is enough for orchagent to process the request and respone freeze or not
+    for i in `seq 4 -1 0`; do
+        docker exec -i swss /usr/bin/orchagent_restart_check -w 1000 && break
+        echo "RESTARTCHECK failed $i\n" >&2
+        if [[ "$i" = "0" ]]; then
+            echo "RESTARTCHECK failed finally\n" >&2
+            exit 10
+        fi
+    done
 fi
 
 # Kill bgpd to start the bgp graceful restart procedure
