add a check to handle failures when there's no ACL_ENTRY objects found

diff --git a/scripts/fast-reboot b/scripts/fast-reboot
--- a/scripts/fast-reboot
+++ b/scripts/fast-reboot
@@ -275,13 +275,22 @@ function backup_database()
 
 function check_mirror_session_acls()
 {
+    debug "Checking if mirror session ACLs (arp, nd) programmed to ASIC successfully"
     ACL_ARP="missing"
     ACL_ND="missing"
     start_time=${SECONDS}
     elapsed_time=$((${SECONDS} - ${start_time}))
     while [[ ${elapsed_time} -lt 10 ]]; do
         ACL_ENTRIES=( $(redis-cli -n 1 KEYS "*" | grep SAI_OBJECT_TYPE_ACL_ENTRY) )
+	if [[ $? -ne 0 ]]; then
+	    error "Failed to retrieve from redis"
+	    exit ${EXIT_NO_MIRROR_SESSION_ACLS}
+	fi
         ACL_COUNT=${#ACL_ENTRIES[@]}
+	if [[ ${ACL_COUNT} -eq 0 ]]; then
+	    error "NO ACL_ENTRY objects found"
+	    exit ${EXIT_NO_MIRROR_SESSION_ACLS}
+	fi
         for ACL_ENTRY in ${ACL_ENTRIES[@]}; do
             ACL_PRIORITY=$(redis-cli -n 1 HGET ${ACL_ENTRY} SAI_ACL_ENTRY_ATTR_PRIORITY)
             if [[ ${ACL_PRIORITY} -eq 8888 ]]; then
@@ -298,7 +307,7 @@ function check_mirror_session_acls()
         elapsed_time=$((${SECONDS} - ${start_time}))
     done
     if [[ "${ACL_ARP}" != "found" || "${ACL_ND}" != "found" ]]; then
-        error "Failed to program mirror session ACLs on ASIC. ACLs: ARP=${ACL_ARP} ND=${ACL_ND}"
+        debug "Failed to program mirror session ACLs on ASIC. ACLs: ARP=${ACL_ARP} ND=${ACL_ND}"
         exit ${EXIT_NO_MIRROR_SESSION_ACLS}
     fi
     debug "Mirror session ACLs (arp, nd) programmed to ASIC successfully"
