Move the teamd retry count check to before orchagent
This is so that in the case of the teamd retry count check failing,
there's fewer changes that happen on the system (it'll fail faster).

Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>

diff --git a/scripts/fast-reboot b/scripts/fast-reboot
--- a/scripts/fast-reboot
+++ b/scripts/fast-reboot
@@ -644,6 +644,22 @@ init_warm_reboot_states
 
 setup_control_plane_assistant
 
+TEAMD_INCREASE_RETRY_COUNT=0
+if [[ "${REBOOT_TYPE}" = "warm-reboot" || "${REBOOT_TYPE}" = "fastfast-reboot" ]]; then
+	TEAMD_RETRY_COUNT_PROBE_RC=0
+    /usr/local/bin/teamd_increase_retry_count.py --probe-only || TEAMD_RETRY_COUNT_PROBE_RC=$?
+    if [[ $TEAMD_RETRY_COUNT_PROBE_RC -ne 0 ]]; then
+        if [[ "${REQUIRE_TEAMD_RETRY_COUNT}" = "yes" ]]; then
+            error "Could not confirm that all neighbor devices are running SONiC with the retry count feature"
+        else
+            debug "Warning: Retry count feature support unknown for one or more neighbor devices; assuming that it's not available"
+            TEAMD_INCREASE_RETRY_COUNT=0
+        fi
+    else
+        TEAMD_INCREASE_RETRY_COUNT=1
+    fi
+fi
+
 if [[ "$REBOOT_TYPE" = "warm-reboot" || "$REBOOT_TYPE" = "fastfast-reboot" || "$REBOOT_TYPE" = "fast-reboot" ]]; then
     # Freeze orchagent for warm restart
     # Ask orchagent_restart_check to try freeze 5 times with interval of 2 seconds,
@@ -669,22 +685,6 @@ if [[ "$REBOOT_TYPE" = "fast-reboot" ]]; then
         error "Failed to delay counterpoll. Exit code: $COUNTERPOLL_DELAY_RC"
         unload_kernel
         exit "${EXIT_COUNTERPOLL_DELAY_FAILURE}"
-    fi
-fi
-
-TEAMD_INCREASE_RETRY_COUNT=0
-if [[ "${REBOOT_TYPE}" = "warm-reboot" || "${REBOOT_TYPE}" = "fastfast-reboot" ]]; then
-	TEAMD_RETRY_COUNT_PROBE_RC=0
-    /usr/local/bin/teamd_increase_retry_count.py --probe-only || TEAMD_RETRY_COUNT_PROBE_RC=$?
-    if [[ $TEAMD_RETRY_COUNT_PROBE_RC -ne 0 ]]; then
-        if [[ "${REQUIRE_TEAMD_RETRY_COUNT}" = "yes" ]]; then
-            error "Could not confirm that all neighbor devices are running SONiC with the retry count feature"
-        else
-            debug "Warning: Retry count feature support unknown for one or more neighbor devices; assuming that it's not available"
-            TEAMD_INCREASE_RETRY_COUNT=0
-        fi
-    else
-        TEAMD_INCREASE_RETRY_COUNT=1
     fi
 fi
 
