[warm reboot] pre-shutdown syncd during warm reboot
Signed-off-by: Ying Xie <ying.xie@microsoft.com>

diff --git a/scripts/fast-reboot b/scripts/fast-reboot
--- a/scripts/fast-reboot
+++ b/scripts/fast-reboot
@@ -25,6 +25,39 @@ function clear_warm_boot()
     fi
 }
 
+function initialize_pre_shutdown()
+{
+    TABLE="WARM_RESTART_TABLE|warm-shutdown"
+    RESTORE_COUNT=`/usr/bin/redis-cli -n 6 hget "${TABLE}" restore_count`
+    if [[ -z "$RESTORE_COUNT" ]]; then
+        /usr/bin/redis-cli -n 6 hset "${TABLE}" restore_count 0
+    fi
+    /usr/bin/redis-cli -n 6 hset "${TABLE}" state requesting
+}
+
+function request_pre_shutdown()
+{
+    /usr/bin/docker exec -i syncd /usr/bin/syncd_request_shutdown --pre
+}
+
+function wait_for_pre_shutdown_complete_or_fail()
+{
+    TABLE="WARM_RESTART_TABLE|warm-shutdown"
+    STATE="requesting"
+    while /bin/true; do
+        STATE=`/usr/bin/redis-cli -n 6 hget "${TABLE}" state`
+        if [[ x"${STATE}" != x"requesting" ]]; then
+            break
+        fi
+        sleep 0.1
+    done
+
+    if [[ x"${STATE}" != x"pre-shutdown-succeeded" ]]; then
+        echo "Syncd pre-shutdown failed: ${STATE} ..."
+        exit 10
+    fi
+}
+
 # Check reboot type supported
 BOOT_TYPE_ARG="cold"
 case "$REBOOT_TYPE" in
@@ -115,14 +148,6 @@ docker exec -i bgp pkill -9 bgpd
 # Kill lldp, otherwise it sends informotion about reboot
 docker kill lldp > /dev/null
 
-# Stop teamd gracefully
-if [[ "$REBOOT_TYPE" = "warm-reboot" ]]; then
-    # Send USR1 signal to all teamd instances to stop them
-    # It will prepare teamd for warm-reboot
-    # Note: We must send USR1 signal before syncd, because it will send the last packet through CPU port
-    docker exec -i teamd pkill -USR1 teamd > /dev/null
-fi
-
 if [[ "$REBOOT_TYPE" = "fast-reboot" ]]; then
     # Kill teamd, otherwise it gets down all LAGs
     # Note: teamd must be killed before syncd, because it will send the last packet through CPU port
@@ -132,6 +157,20 @@ fi
 
 # Kill swss dockers
 docker kill swss
+
+# Pre-shtudown syncd and Stop teamd gracefully
+if [[ "$REBOOT_TYPE" = "warm-reboot" ]]; then
+    initialize_pre_shutdown
+
+    request_pre_shutdown
+
+    wait_for_pre_shutdown_complete_or_fail
+
+    # Send USR1 signal to all teamd instances to stop them
+    # It will prepare teamd for warm-reboot
+    # Note: We must send USR1 signal before syncd, because it will send the last packet through CPU port
+    docker exec -i teamd pkill -USR1 teamd > /dev/null
+fi
 
 # syncd service stop is capable of handling both warm/fast/cold shutdown
 systemctl stop syncd
