[warm-reboot]: added pre-check for ISSU file
Signed-off-by: Vadym Hlushko <vadymh@mellanox.com>

diff --git a/scripts/fast-reboot b/scripts/fast-reboot
--- a/scripts/fast-reboot
+++ b/scripts/fast-reboot
@@ -156,6 +156,42 @@ function request_pre_shutdown()
     }
 }
 
+function recover_issu_bank_file_instruction()
+{
+    error "To recover (${ISSU_BANK_FILE}) file, do the following:"
+    error "$ docker exec -it syncd sx_api_dbg_generate_dump.py"
+    error "$ docker exec -it syncd cat /tmp/sdkdump | grep 'ISSU Bank'"
+    error "Command above will print the VALUE of ISSU BANK - 0 or 1, use this VALUE in the next command"
+    error "$ printf VALUE > /host/warmboot/issu_bank.txt"
+}
+
+function check_issu_bank_file()
+{
+    ISSU_BANK_FILE=/host/warmboot/issu_bank.txt
+    MLNX_ISSU_BANK_BROKEN=102
+
+    if [[ ! -s "$ISSU_BANK_FILE" ]]; then
+        error "(${ISSU_BANK_FILE}) does NOT exist or empty ..."
+        recover_issu_bank_file_instruction
+        exit "${MLNX_ISSU_BANK_BROKEN}"
+    fi
+
+    issu_file_chars_count=`wc -m ${ISSU_BANK_FILE} | awk '{print $1}'`;
+    if [[ $issu_file_chars_count != 1 ]]; then
+        error "(${ISSU_BANK_FILE}) characters count is NOT valid ..."
+        recover_issu_bank_file_instruction
+        exit "${MLNX_ISSU_BANK_BROKEN}"
+    fi
+
+    issu_file_content=`awk '{print $0}' ${ISSU_BANK_FILE}`
+    if [[ "$issu_file_content" != "0" && "$issu_file_content" != "1" ]]; then
+        error "(${ISSU_BANK_FILE}) has invalid content ..."
+        recover_issu_bank_file_instruction
+        exit "${MLNX_ISSU_BANK_BROKEN}"
+    fi
+}
+
+
 function wait_for_pre_shutdown_complete_or_fail()
 {
     debug "Waiting for pre-shutdown ..."
@@ -483,7 +519,15 @@ systemctl stop swss
 if [[ "$REBOOT_TYPE" = "warm-reboot" || "$REBOOT_TYPE" = "fastfast-reboot" ]]; then
     initialize_pre_shutdown
 
+    if [[ "x$sonic_asic_type" == x"mellanox" ]]; then
+        check_issu_bank_file
+    fi
+
     request_pre_shutdown
+
+    if [[ "x$sonic_asic_type" == x"mellanox" ]]; then
+        check_issu_bank_file
+    fi
 
     wait_for_pre_shutdown_complete_or_fail
 
