Exit instead of restart and minor refactoring
Signed-off-by: Vivek Reddy Karri <vkarri@nvidia.com>

diff --git a/scripts/generate_dump b/scripts/generate_dump
--- a/scripts/generate_dump
+++ b/scripts/generate_dump
@@ -6,9 +6,14 @@
 
 set -u
 
-ERROR_TAR_FAILED=5
-ERROR_PROCFS_SAVE_FAILED=6
-ERROR_INVALID_ARGUMENT=10
+EXT_SUCCESS=0
+EXT_GENERAL=1
+EXT_LOCKFAIL=2
+EXT_RECVSIG=3
+EXT_RETRY=4
+EXT_TAR_FAILED=5
+EXT_PROCFS_SAVE_FAILED=6
+EXT_INVALID_ARGUMENT=10
 
 TAR=tar
 MKDIR=mkdir
@@ -42,11 +47,6 @@ SAVE_STDERR=true
 RETURN_CODE=0
 DEBUG_DUMP=false
 
-EXT_SUCCESS=0; ETMP[0]="EXT_SUCCESS"
-EXT_GENERAL=1; ETMP[1]="EXT_GENERAL"
-EXT_LOCKFAIL=2; ETMP[2]="EXT_LOCKFAIL"
-EXT_RECVSIG=3; ETMP[3]="EXT_RECVSIG"
-
 # lock dirs/files
 LOCKDIR="/tmp/techsupport-lock"
 PIDFILE="${LOCKDIR}/PID"
@@ -62,7 +62,7 @@ rm_lock_and_restart()
 handle_exit()
 {
     ECODE=$?
-    echo "Removing lock. Exit: ${ETMP[ECODE]}($ECODE)" >&2
+    echo "Removing lock. Exit: $ECODE" >&2
     $RM $V -rf ${LOCKDIR}
 }
 
@@ -126,7 +126,7 @@ save_bcmcmd() {
         filepath="${filepath}.gz"
     fi
     ($TAR $V -rhf $TARFILE -C $DUMPDIR "$tarpath" \
-        || abort "${ERROR_TAR_FAILED}" "tar append operation failed. Aborting to prevent data loss.") \
+        || abort "${EXT_TAR_FAILED}" "tar append operation failed. Aborting to prevent data loss.") \
         && $RM $V -rf "$filepath"
     end_t=$(date +%s%3N)
     echo "[ save_bcmcmd:$cmd ] : $(($end_t-$start_t)) msec" >> $TECHSUPPORT_TIME_INFO
@@ -236,7 +236,7 @@ save_cmd() {
     fi
 
     ($TAR $V -rhf $TARFILE -C $DUMPDIR "$tarpath" \
-        || abort "${ERROR_TAR_FAILED}" "tar append operation failed. Aborting to prevent data loss.") \
+        || abort "${EXT_TAR_FAILED}" "tar append operation failed. Aborting to prevent data loss.") \
         && $RM $V -rf "$filepath"
     end_t=$(date +%s%3N)
     echo "[ save_cmd:$cmd ] : $(($end_t-$start_t)) msec" >> $TECHSUPPORT_TIME_INFO
@@ -789,7 +789,7 @@ save_file() {
 
     if $do_tar_append; then
         ($TAR $V -rhf $TARFILE -C $DUMPDIR "$tar_path" \
-            || abort "${ERROR_PROCFS_SAVE_FAILED}" "tar append operation failed. Aborting to prevent data loss.") \
+            || abort "${EXT_PROCFS_SAVE_FAILED}" "tar append operation failed. Aborting to prevent data loss.") \
             && $RM $V -f "$gz_path"
     fi
     end_t=$(date +%s%3N)
@@ -998,7 +998,7 @@ save_log_files() {
 
     # Append the log folder to the main tarball
     ($TAR $V -rhf $TARFILE -C $DUMPDIR ${BASE}/log \
-        || abort "${ERROR_TAR_FAILED}" "tar append operation failed. Aborting for safety") \
+        || abort "${EXT_TAR_FAILED}" "tar append operation failed. Aborting for safety") \
         && $RM $V -rf $TARDIR/log
     end_t=$(date +%s%3N)
     echo "[ TAR /var/log Files ] : $(($end_t-$start_t)) msec" >> $TECHSUPPORT_TIME_INFO
@@ -1027,7 +1027,7 @@ save_warmboot_files() {
 
         ($TAR $V --warning=no-file-removed  -rhf $TARFILE -C $DUMPDIR --mode=+rw \
             $BASE/warmboot \
-            || abort "${ERROR_TAR_FAILED}" "Tar append operation failed. Aborting for safety.") \
+            || abort "${EXT_TAR_FAILED}" "Tar append operation failed. Aborting for safety.") \
             && $RM $V -rf $TARDIR
     fi
     end_t=$(date +%s%3N)
@@ -1192,7 +1192,7 @@ main() {
         /proc/softirqs /proc/stat /proc/swaps /proc/sysvipc /proc/timer_list \
         /proc/uptime /proc/version /proc/vmallocinfo /proc/vmstat \
         /proc/zoneinfo \
-        || abort "${ERROR_PROCFS_SAVE_FAILED}" "Proc saving operation failed. Aborting for safety."
+        || abort "${EXT_PROCFS_SAVE_FAILED}" "Proc saving operation failed. Aborting for safety."
     end_t=$(date +%s%3N)
     echo "[ Capture Proc State ] : $(($end_t-$start_t)) msec" >> $TECHSUPPORT_TIME_INFO
 
@@ -1325,7 +1325,7 @@ main() {
         --exclude="*/etc/ssl/certs/*" \
         --exclude="*/etc/ssl/private/*" \
         $BASE/etc \
-        || abort "${ERROR_TAR_FAILED}" "Tar append operation failed. Aborting for safety.") \
+        || abort "${EXT_TAR_FAILED}" "Tar append operation failed. Aborting for safety.") \
         && $RM $V -rf $TARDIR
     end_t=$(date +%s%3N)
     echo "[ TAR /etc Files ] : $(($end_t-$start_t)) msec" >> $TECHSUPPORT_TIME_INFO
@@ -1519,7 +1519,7 @@ while getopts ":xnvhzas:t:r:d" opt; do
         s)
             SINCE_DATE="${OPTARG}"
             # validate date expression
-            date --date="${SINCE_DATE}" &> /dev/null || abort "${ERROR_INVALID_ARGUMENT}" "Invalid date expression passed: '${SINCE_DATE}'"
+            date --date="${SINCE_DATE}" &> /dev/null || abort "${EXT_INVALID_ARGUMENT}" "Invalid date expression passed: '${SINCE_DATE}'"
             ;;
         t)
             TIMEOUT_MIN="${OPTARG}"
@@ -1541,7 +1541,7 @@ done
 if [ `whoami` != root ] && ! $NOOP;
 then
     echo "$0: must be run as root (or in sudo)" >&2
-    exit $ERROR_INVALID_ARGUMENT
+    exit $EXT_INVALID_ARGUMENT
 fi
 
 ##
@@ -1563,9 +1563,8 @@ else
 
     if [ $? != 0 ]; then
         # Another instance is probably about to remove the lock or PIDfile doesn't exist
-        # Wait for a few secs and restart
-        sleep "$(( $RANDOM % 2 + 1)).$(( $RANDOM % 999 ))"
-        rm_lock_and_restart
+        # Exit and let user decide if they want to restart
+        exit $EXT_RETRY
     fi
 
     if ! kill -0 $PID_PROG &>/dev/null; then
