[generate_dump] Ignoring file/directory not found errors
Signed-off-by: Sabareesh Kumar Anandan <sanandan@marvell.com>

diff --git a/scripts/generate_dump b/scripts/generate_dump
--- a/scripts/generate_dump
+++ b/scripts/generate_dump
@@ -326,7 +326,7 @@ save_redis_info() {
 save_proc() {
     local procfiles="$@"
     $MKDIR $V -p $TARDIR/proc \
-        && $CP $V -r $procfiles $TARDIR/proc \
+	    && (for f in $procfiles; do ( [ -e $f ] && $CP $V -r $f $TARDIR/proc ) || echo "$f not found" > $TARDIR/$f; done) \
         && $TAR $V -rhf $TARFILE -C $DUMPDIR --mode=+rw $BASE/proc \
         && $RM $V -rf $TARDIR/proc
 }
@@ -615,7 +615,7 @@ save_crash_files() {
     done
 
     # archive kernel dump files
-    for file in $(find_files "/var/crash/"); do
+    [ -e /var/crash/ ] && for file in $(find_files "/var/crash/"); do
         # don't gzip already-gzipped dmesg files :)
         if [ ! ${file} = "/var/crash/kexec_cmd" -a ! ${file} = "/var/crash/export" ]; then
             if [[ ${file} == *"kdump."* ]]; then
@@ -742,7 +742,7 @@ main() {
     $MKDIR $V -p $LOGDIR
     $LN $V -s /etc $TARDIR/etc
 
-    ($TAR $V -rhf $TARFILE -C $DUMPDIR --mode=+rw \
+    ($TAR $V -rf $TARFILE -C $DUMPDIR --mode=+rw \
         --exclude="etc/alternatives" \
         --exclude="*/etc/passwd*" \
         --exclude="*/etc/shadow*" \
