Fix PR comments, improve cleanup method to work with pipeline and gzip.

diff --git a/scripts/generate_dump b/scripts/generate_dump
--- a/scripts/generate_dump
+++ b/scripts/generate_dump
@@ -166,9 +166,9 @@ save_cmd() {
     local filename=$2
     local filepath="${LOGDIR}/$filename"
     local do_gzip=${3:-false}
-    local cleanup_method=${4:-null}
     local tarpath="${BASE}/dump/$filename"
     local timeout_cmd="timeout --foreground ${TIMEOUT_MIN}m"
+    local cleanup_method=${4:-dummy_cleanup_method}
     local redirect='&>'
     local redirect_eval='2>&1'
     if [ ! -d $LOGDIR ]; then
@@ -181,13 +181,6 @@ save_cmd() {
         redirect_eval=""
     fi
 
-    # Cleanup method need do post procress on dump file.
-    if [ ! -z "$cleanup_method" ]
-    then
-        echo "Disable gzip for dump '$filepath'"
-        do_gzip=false
-    fi
-
     # eval required here to re-evaluate the $cmd properly at runtime
     # This is required if $cmd has quoted strings that should be bunched
     # as one argument, e.g. vtysh -c "COMMAND HERE" needs to have
@@ -195,7 +188,9 @@ save_cmd() {
     if $do_gzip; then
         tarpath="${tarpath}.gz"
         filepath="${filepath}.gz"
-        local cmds="$cmd $redirect_eval | gzip -c > '${filepath}'"
+        # cleanup_method will run in a sub-shell, need declare it first
+        local cleanup_method_declration=$(declare -f $cleanup_method)
+        local cmds="$cleanup_method_declration; $cmd $redirect_eval | $cleanup_method | gzip -c > '${filepath}'"
         if $NOOP; then
             echo "${timeout_cmd} bash -c \"${cmds}\""
         else
@@ -207,27 +202,34 @@ save_cmd() {
         fi
     else
         if $NOOP; then
-            echo "${timeout_cmd} $cmd $redirect '$filepath'"
+            echo "${timeout_cmd} $cmd | $cleanup_method $redirect '$filepath'"
         else
             RC=0
-            eval "${timeout_cmd} $cmd" "$redirect" "$filepath" || RC=$?
+            eval "${timeout_cmd} $cmd | $cleanup_method" "$redirect" "$filepath" || RC=$?
             if [ $RC -ne 0 ]; then
                 echo "Command: $cmd timedout after ${TIMEOUT_MIN} minutes."
             fi
         fi
     fi
 
-    if [ ! -z "$cleanup_method" ]
-    then
-        echo "Run cleanup method for '$filepath'"
-        $cleanup_method $filepath
-    fi
-    
     ($TAR $V -rhf $TARFILE -C $DUMPDIR "$tarpath" \
         || abort "${ERROR_TAR_FAILED}" "tar append operation failed. Aborting to prevent data loss.") \
         && $RM $V -rf "$filepath"
     end_t=$(date +%s%3N)
     echo "[ save_cmd:$cmd ] : $(($end_t-$start_t)) msec" >> $TECHSUPPORT_TIME_INFO
+}
+
+###############################################################################
+# Dummy cleanup method.
+# Globals:
+#  None
+# Arguments:
+#  None
+# Returns:
+#  None
+###############################################################################
+dummy_cleanup_method() {
+    cat
 }
 
 ###############################################################################
@@ -1280,7 +1282,7 @@ main() {
     fi
 
     # Remove secret from /etc files before tar
-    remove_secret_from_etc_files
+    remove_secret_from_etc_files $TARDIR
 
     start_t=$(date +%s%3N)
     ($TAR $V --warning=no-file-removed -rhf $TARFILE -C $DUMPDIR --mode=+rw \
@@ -1341,23 +1343,17 @@ main() {
 }
 
 ###############################################################################
-# Remove secret from Config DB dump files.
+# Remove secret from pipeline inout and output result to pipeline.
 # Globals:
 #  None
 # Arguments:
-#  filepath: the filepath to save the output as in $BASE/dump.
+#  None
 # Returns:
 #  None
 ###############################################################################
 remove_secret_from_config_db_dump() {
-    local filepath=$1
-    echo "Remove secret from '$filepath' files."
-
-    # Remove tacacs & radius passkey from config DB
-    sed -i -E 's/\"passkey\"\s*:\s*\"([^\"]*)\"/\"passkey\":\"****\"/g' $filepath
-
-    # Remove snmp community from config DB
-    sed -i -E '/SNMP_COMMUNITY/,/\s{2,4}\},/d' $filepath
+    # Remove tacacs & radius passkey and snmp community from config DB
+    sed -E 's/\"passkey\"\s*:\s*\"([^\"]*)\"/\"passkey\":\"****\"/g; /SNMP_COMMUNITY/,/\s{2,4}\},/d'
 }
 
 ###############################################################################
@@ -1393,7 +1389,8 @@ remove_secret_from_etc_files() {
     sed -i -E 's/(\s*snmp_\S*community\s*:\s*)(\S*)/\1****/g' $dumppath/etc/sonic/snmp.yml
     
     # Remove secret from /etc/sonic/config_db.json
-    remove_secret_from_config_db_dump $dumppath/etc/sonic/config_db.json
+    cat $dumppath/etc/sonic/config_db.json | remove_secret_from_config_db_dump > $dumppath/etc/sonic/config_db.json.temp
+    mv $dumppath/etc/sonic/config_db.json.temp $dumppath/etc/sonic/config_db.json
 }
 
 ###############################################################################
