[generate_dump] add specific error codes
Signed-off-by: Stepan Blyschak <stepanb@mellanox.com>

diff --git a/scripts/generate_dump b/scripts/generate_dump
--- a/scripts/generate_dump
+++ b/scripts/generate_dump
@@ -6,6 +6,10 @@
 
 set -u
 
+ERROR_TAR_FAILED=5
+ERROR_PROCFS_SAVE_FAILED=6
+ERROR_INVALID_ARGUMENT=10
+
 TAR=tar
 MKDIR=mkdir
 RM=rm
@@ -74,7 +78,7 @@ save_cmd() {
         fi
     fi
     ($TAR $V -rhf $TARFILE -C $DUMPDIR "$tarpath" \
-        || abort 5 "tar append operation failed. Aborting to prevent data loss.") \
+        || abort "${ERROR_TAR_FAILED}" "tar append operation failed. Aborting to prevent data loss.") \
         && $RM $V -rf "$filepath"
 }
 
@@ -214,7 +218,7 @@ save_file() {
         fi
     fi
     ($TAR $V -rhf $TARFILE -C $DUMPDIR "$tar_path" \
-        || abort 5 "tar append operation failed. Aborting to prevent data loss.") \
+        || abort "${ERROR_PROCFS_SAVE_FAILED}" "tar append operation failed. Aborting to prevent data loss.") \
         && $RM $V -f "$gz_path"
 }
 
@@ -282,7 +286,7 @@ main() {
         /proc/softirqs /proc/stat /proc/swaps /proc/sysvipc /proc/timer_list \
         /proc/uptime /proc/version /proc/vmallocinfo /proc/vmstat \
         /proc/zoneinfo \
-        || abort 6 "Proc saving operation failed. Aborting for safety."
+        || abort "${ERROR_PROCFS_SAVE_FAILED}" "Proc saving operation failed. Aborting for safety."
 
     save_cmd "show version" "version"
     save_cmd "show platform summary" "platform.summary"
@@ -367,7 +371,7 @@ main() {
         --exclude="*get_creds*" \
         --exclude="*snmpd.conf*" \
         $BASE/etc \
-        || abort 5 "Tar append operation failed. Aborting for safety.") \
+        || abort "${ERROR_TAR_FAILED}" "Tar append operation failed. Aborting for safety.") \
         && $RM $V -rf $TARDIR
 
     # gzip up all log files individually before placing them in the incremental tarball
@@ -494,7 +498,7 @@ while getopts ":xnvhzs:" opt; do
         s)
             SINCE_DATE="${OPTARG}"
             # validate date expression
-            date --date="${SINCE_DATE}" &> /dev/null || abort 10 "Invalid date expression passed: '${SINCE_DATE}'"
+            date --date="${SINCE_DATE}" &> /dev/null || abort "${ERROR_INVALID_ARGUMENT}" "Invalid date expression passed: '${SINCE_DATE}'"
             ;;
         /?)
             echo "Invalid option: -$OPTARG" >&2
