add NOOP option for save_proc and docker cp commands

diff --git a/scripts/generate_dump b/scripts/generate_dump
--- a/scripts/generate_dump
+++ b/scripts/generate_dump
@@ -215,6 +215,71 @@ save_cmd_all_ns() {
 }
 
 ###############################################################################
+# Copies a given file from a specified docker to the given target location
+# default (host) namespace in single ASIC platform
+# Globals:
+#  None
+# Arguments:
+#  docker: docker name
+#  filename: the filename to copy
+#  destination: destination filename
+# Returns:
+#  None
+###############################################################################
+copy_from_docker() {
+    local start_t=$(date +%s%3N)
+    local end_t=0
+    local docker=$1
+    local filename=$2
+    local dstpath=$3
+    local timeout_cmd="timeout --foreground ${TIMEOUT_MIN}m"
+
+    if $NOOP; then
+        echo "${timeout_cmd} sudo docker exec -i ${docker} touch ${filename}"
+        echo "${timeout_cmd} sudo docker cp ${docker}:${filename} ${dstpath}"
+    else
+        eval "${timeout_cmd} sudo docker exec -i ${docker} touch ${filename}"
+        if [ $? -ne 0 ]; then
+            echo "Command: $cmd timedout after ${TIMEOUT_MIN} minutes."
+        fi
+        eval "${timeout_cmd} sudo docker cp ${docker}:${filename} ${dstpath}"
+        if [ $? -ne 0 ]; then
+            echo "Command: $cmd timedout after ${TIMEOUT_MIN} minutes."
+        fi
+    fi
+    end_t=$(date +%s%3N)
+    echo "[ copy_from_docker:${docker}:${filename} ] : $(($end_t-$start_t)) msec" \
+        >> $TECHSUPPORT_TIME_INFO
+}
+
+###############################################################################
+# Copies a given file from a specified docker to the given target location
+# default (host) namespace in single ASIC platform
+# Globals:
+#  NUM_ASICS
+# Arguments:
+#  docker: docker name
+#  filename: the filename to copy
+#  destination: destination filename
+# Returns:
+#  None
+###############################################################################
+copy_from_masic_docker() {
+    local docker=$1
+    local filename=$2
+    local dstpath=$3
+
+    if [[ ("$NUM_ASICS" > 1) ]]; then
+        for (( i=0; i<$NUM_ASICS; i++ ))
+        do
+            copy_from_docker "$docker$i" "$filename" "$dstpath.$i"
+        done
+    else
+        copy_from_docker "$docker" "$filename" "$dstpath"
+    fi
+}
+
+###############################################################################
 # Returns namespace option to be used with vtysh commmand, based on the ASIC ID.
 # Returns empty string if no ASIC ID is provided
 # Globals:
@@ -493,6 +558,7 @@ save_redis_info() {
 #  RM
 #  BASE
 #  TARFILE
+#  NOOP
 # Arguments:
 #  *procfiles: variable-length list of proc file paths to save
 # Returns:
@@ -500,10 +566,20 @@ save_redis_info() {
 ###############################################################################
 save_proc() {
     local procfiles="$@"
-    $MKDIR $V -p $TARDIR/proc \
-        && (for f in $procfiles; do ( [ -e $f ] && $CP $V -r $f $TARDIR/proc ) || echo "$f not found" > $TARDIR/$f; done) \
-        && $TAR $V -rhf $TARFILE -C $DUMPDIR --mode=+rw $BASE/proc \
-        && $RM $V -rf $TARDIR/proc
+    $MKDIR $V -p $TARDIR/proc
+    for f in $procfiles
+    do
+        if $NOOP; then
+            if [ -e $f ]
+            then
+                echo "$CP $V -r $f $TARDIR/proc"
+            fi
+        else
+            ( [ -e $f ] && $CP $V -r $f $TARDIR/proc ) || echo "$f not found" > $TARDIR/$f
+        fi
+    done
+    $TAR $V -rhf $TARFILE -C $DUMPDIR --mode=+rw $BASE/proc
+    $RM $V -rf $TARDIR/proc
 }
 
 ###############################################################################
@@ -800,6 +876,9 @@ collect_broadcom() {
     save_bcmcmd_all_ns "\"mirror dest show\"" "mirror.dest.summary"
     save_bcmcmd_all_ns "\"port *\"" "port.summary"
     save_bcmcmd_all_ns "\"d chg my_station_tcam\"" "mystation.tcam.summary"
+
+    copy_from_masic_docker "syncd" "/var/log/diagrun.log" "/var/log/diagrun.log"
+    copy_from_masic_docker "syncd" "/var/log/bcm_diag_post" "/var/log/bcm_diag_post"
 }
 
 ###############################################################################
@@ -859,7 +938,7 @@ save_log_files() {
 ###############################################################################
 # Save warmboot files
 # Globals:
-#  TARDIR, TARFILE, TAR, DUMPDIR, TECHSUPPORT_TIME_INFO
+#  TARDIR, TARFILE, TAR, DUMPDIR, TECHSUPPORT_TIME_INFO, NOOP
 # Arguments:
 #  None
 # Returns:
@@ -867,16 +946,20 @@ save_log_files() {
 ###############################################################################
 save_warmboot_files() {
     # Copy the warmboot files
-    mkdir -p $TARDIR
-    $CP $V -rf /host/warmboot $TARDIR
+    if $NOOP; then
+        echo "$CP $V -rf /host/warmboot $TARDIR"
+    else
+        mkdir -p $TARDIR
+        $CP $V -rf /host/warmboot $TARDIR
 
-    start_t=$(date +%s%3N)
-    ($TAR $V --warning=no-file-removed  -rhf $TARFILE -C $DUMPDIR --mode=+rw \
-        $BASE/warmboot \
-        || abort "${ERROR_TAR_FAILED}" "Tar append operation failed. Aborting for safety.") \
-        && $RM $V -rf $TARDIR
-    end_t=$(date +%s%3N)
-    echo "[ Warm-boot Files ] : $(($end_t-$start_t)) msec" >> $TECHSUPPORT_TIME_INFO
+        start_t=$(date +%s%3N)
+        ($TAR $V --warning=no-file-removed  -rhf $TARFILE -C $DUMPDIR --mode=+rw \
+            $BASE/warmboot \
+            || abort "${ERROR_TAR_FAILED}" "Tar append operation failed. Aborting for safety.") \
+            && $RM $V -rf $TARDIR
+        end_t=$(date +%s%3N)
+        echo "[ Warm-boot Files ] : $(($end_t-$start_t)) msec" >> $TECHSUPPORT_TIME_INFO
+    fi
 }
 
 ###############################################################################
@@ -1122,24 +1205,6 @@ main() {
     end_t=$(date +%s%3N)
     echo "[ TAR /etc Files ] : $(($end_t-$start_t)) msec" >> $TECHSUPPORT_TIME_INFO
 
-    if [ "$asic" = "broadcom" ]; then
-        if [[ ("$NUM_ASICS" > 1) ]]; then
-            for (( i=0; i<$NUM_ASICS; i++ ))
-            do
-                sudo docker exec -i syncd$i touch /var/log/diagrun.log
-                sudo docker exec -i syncd$i touch /var/log/bcm_diag_post
-
-                sudo docker cp syncd$i:/var/log/diagrun.log /var/log/diagrun.log.$i
-                sudo docker cp syncd$i:/var/log/bcm_diag_post /var/log/bcm_diag_post.$i
-            done
-        else
-           sudo docker exec -i syncd touch /var/log/diagrun.log
-           sudo docker exec -i syncd touch /var/log/bcm_diag_post
-
-           sudo docker cp syncd:/var/log/diagrun.log /var/log/diagrun.log
-           sudo docker cp syncd:/var/log/bcm_diag_post /var/log/bcm_diag_post
-        fi
-    fi
     save_log_files
     save_warmboot_files
     save_crash_files
